import { Decimal } from "decimal.js"

// 顧客モックデータ
export const customers = [
  { id: "cust1", name: "株式会社テクノロジー" },
  { id: "cust2", name: "株式会社イノベーション" },
  { id: "cust3", name: "株式会社デジタルソリューション" },
  { id: "cust4", name: "株式会社クラウドサービス" },
  { id: "cust5", name: "株式会社データアナリティクス" },
]

// 商品モックデータ
export const products = [
  { id: "prod1", name: "エンタープライズライセンス", type: "LICENSE", description: "企業向け基本ライセンス" },
  { id: "prod2", name: "プレミアムライセンス", type: "LICENSE", description: "高機能ライセンス" },
  { id: "prod3", name: "コンサルティングサービス", type: "SERVICE", description: "導入支援コンサルティング" },
  { id: "prod4", name: "カスタマイズ開発", type: "SERVICE", description: "カスタム機能開発" },
  { id: "prod5", name: "トレーニングサービス", type: "SERVICE", description: "ユーザートレーニング" },
]

// 商談モックデータ
export const deals = [
  {
    id: "deal1",
    name: "株式会社テクノロジー 基本契約",
    customerId: "cust1",
    customerName: "株式会社テクノロジー",
    dealDate: new Date("2024-01-15"),
    fiscalYear: 2024,
    fiscalQuarter: 1,
    type: "MIXED",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "deal2",
    name: "株式会社イノベーション 年間契約",
    customerId: "cust2",
    customerName: "株式会社イノベーション",
    dealDate: new Date("2024-02-10"),
    fiscalYear: 2024,
    fiscalQuarter: 1,
    type: "LICENSE",
    createdAt: new Date("2024-02-10"),
    updatedAt: new Date("2024-02-10"),
  },
  {
    id: "deal3",
    name: "株式会社デジタルソリューション 導入支援",
    customerId: "cust3",
    customerName: "株式会社デジタルソリューション",
    dealDate: new Date("2024-03-05"),
    fiscalYear: 2024,
    fiscalQuarter: 2,
    type: "SERVICE",
    createdAt: new Date("2024-03-05"),
    updatedAt: new Date("2024-03-05"),
  },
  {
    id: "deal4",
    name: "株式会社クラウドサービス 拡張契約",
    customerId: "cust4",
    customerName: "株式会社クラウドサービス",
    dealDate: new Date("2024-04-20"),
    fiscalYear: 2024,
    fiscalQuarter: 2,
    type: "MIXED",
    createdAt: new Date("2024-04-20"),
    updatedAt: new Date("2024-04-20"),
  },
  {
    id: "deal5",
    name: "株式会社データアナリティクス 新規契約",
    customerId: "cust5",
    customerName: "株式会社データアナリティクス",
    dealDate: new Date("2024-05-12"),
    fiscalYear: 2024,
    fiscalQuarter: 3,
    type: "LICENSE",
    createdAt: new Date("2024-05-12"),
    updatedAt: new Date("2024-05-12"),
  },
]

// 新規獲得契約アイテムモックデータ
export const dealItems = [
  {
    id: "item1",
    dealId: "deal1",
    productId: "prod1",
    productName: "エンタープライズライセンス",
    type: "LICENSE",
    amountBeforeTax: new Decimal(1000000),
    amountAfterTax: new Decimal(1100000),
    startDate: new Date("2024-01-01"),
    endDate: new Date("2024-12-31"),
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "item2",
    dealId: "deal1",
    productId: "prod3",
    productName: "コンサルティングサービス",
    type: "SERVICE",
    amountBeforeTax: new Decimal(500000),
    amountAfterTax: new Decimal(550000),
    startDate: new Date("2024-01-15"),
    endDate: new Date("2024-03-15"),
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
  },
  {
    id: "item3",
    dealId: "deal2",
    productId: "prod2",
    productName: "プレミアムライセンス",
    type: "LICENSE",
    amountBeforeTax: new Decimal(1500000),
    amountAfterTax: new Decimal(1650000),
    startDate: new Date("2024-02-01"),
    endDate: new Date("2025-01-31"),
    createdAt: new Date("2024-02-10"),
    updatedAt: new Date("2024-02-10"),
  },
  {
    id: "item4",
    dealId: "deal3",
    productId: "prod4",
    productName: "カスタマイズ開発",
    type: "SERVICE",
    amountBeforeTax: new Decimal(800000),
    amountAfterTax: new Decimal(880000),
    startDate: new Date("2024-03-15"),
    endDate: new Date("2024-06-15"),
    createdAt: new Date("2024-03-05"),
    updatedAt: new Date("2024-03-05"),
  },
  {
    id: "item5",
    dealId: "deal4",
    productId: "prod1",
    productName: "エンタープライズライセンス",
    type: "LICENSE",
    amountBeforeTax: new Decimal(1200000),
    amountAfterTax: new Decimal(1320000),
    startDate: new Date("2024-05-01"),
    endDate: new Date("2025-04-30"),
    createdAt: new Date("2024-04-20"),
    updatedAt: new Date("2024-04-20"),
  },
  {
    id: "item6",
    dealId: "deal4",
    productId: "prod5",
    productName: "トレーニングサービス",
    type: "SERVICE",
    amountBeforeTax: new Decimal(300000),
    amountAfterTax: new Decimal(330000),
    startDate: new Date("2024-05-15"),
    endDate: new Date("2024-07-15"),
    createdAt: new Date("2024-04-20"),
    updatedAt: new Date("2024-04-20"),
  },
  {
    id: "item7",
    dealId: "deal5",
    productId: "prod2",
    productName: "プレミアムライセンス",
    type: "LICENSE",
    amountBeforeTax: new Decimal(2000000),
    amountAfterTax: new Decimal(2200000),
    startDate: new Date("2024-06-01"),
    endDate: new Date("2025-05-31"),
    createdAt: new Date("2024-05-12"),
    updatedAt: new Date("2024-05-12"),
  },
]

// 月次按分売上モックデータを生成
export const generateMonthlySales = () => {
  const monthlySales = []

  // 各契約アイテムに対して月次按分売上を生成
  for (const item of dealItems) {
    const startDate = new Date(item.startDate)
    const endDate = new Date(item.endDate)

    // 契約期間の総日数を計算
    const totalDays = Math.floor((endDate.getTime() - startDate.getTime()) / (1000 * 60 * 60 * 24)) + 1

    // 日割り単価
    const dailyRate = item.amountAfterTax.dividedBy(totalDays)

    // 開始年月と終了年月
    const startYear = startDate.getFullYear()
    const startMonth = startDate.getMonth() + 1 // JavaScriptの月は0始まり
    const endYear = endDate.getFullYear()
    const endMonth = endDate.getMonth() + 1

    // 各月の按分額を計算
    let currentYear = startYear
    let currentMonth = startMonth

    while (currentYear < endYear || (currentYear === endYear && currentMonth <= endMonth)) {
      // 月の日数
      const daysInMonth = new Date(currentYear, currentMonth, 0).getDate()

      // 適用日数を計算
      let applicableDays

      if (currentYear === startYear && currentMonth === startMonth) {
        // 開始月
        const startDay = startDate.getDate()
        applicableDays = daysInMonth - startDay + 1
      } else if (currentYear === endYear && currentMonth === endMonth) {
        // 終了月
        applicableDays = endDate.getDate()
      } else {
        // 中間の月
        applicableDays = daysInMonth
      }

      // 月の按分額
      const amount = dailyRate.times(applicableDays)

      monthlySales.push({
        id: `ms-${item.id}-${currentYear}-${currentMonth}`,
        dealItemId: item.id,
        year: currentYear,
        month: currentMonth,
        totalDays: daysInMonth,
        applicableDays: applicableDays,
        dailyRate: dailyRate,
        amount: amount,
        type: item.type,
        createdAt: new Date(),
        updatedAt: new Date(),
      })

      // 次の月へ
      if (currentMonth === 12) {
        currentYear++
        currentMonth = 1
      } else {
        currentMonth++
      }
    }
  }

  return monthlySales
}

export const monthlySales = generateMonthlySales()

// 費用モックデータ
export const costs = [
  // ライセンス原価
  {
    id: "cost1",
    year: 2024,
    month: 1,
    type: "COST_OF_SALES_LICENSE",
    category: "ライセンス原価",
    amount: new Decimal(200000),
    description: "1月ライセンス原価",
  },
  {
    id: "cost2",
    year: 2024,
    month: 2,
    type: "COST_OF_SALES_LICENSE",
    category: "ライセンス原価",
    amount: new Decimal(220000),
    description: "2月ライセンス原価",
  },
  {
    id: "cost3",
    year: 2024,
    month: 3,
    type: "COST_OF_SALES_LICENSE",
    category: "ライセンス原価",
    amount: new Decimal(230000),
    description: "3月ライセンス原価",
  },
  {
    id: "cost4",
    year: 2024,
    month: 4,
    type: "COST_OF_SALES_LICENSE",
    category: "ライセンス原価",
    amount: new Decimal(240000),
    description: "4月ライセンス原価",
  },
  {
    id: "cost5",
    year: 2024,
    month: 5,
    type: "COST_OF_SALES_LICENSE",
    category: "ライセンス原価",
    amount: new Decimal(250000),
    description: "5月ライセンス原価",
  },

  // サービス原価
  {
    id: "cost6",
    year: 2024,
    month: 1,
    type: "COST_OF_SALES_SERVICE",
    category: "サービス原価",
    amount: new Decimal(150000),
    description: "1月サービス原価",
  },
  {
    id: "cost7",
    year: 2024,
    month: 2,
    type: "COST_OF_SALES_SERVICE",
    category: "サービス原価",
    amount: new Decimal(160000),
    description: "2月サービス原価",
  },
  {
    id: "cost8",
    year: 2024,
    month: 3,
    type: "COST_OF_SALES_SERVICE",
    category: "サービス原価",
    amount: new Decimal(170000),
    description: "3月サービス原価",
  },
  {
    id: "cost9",
    year: 2024,
    month: 4,
    type: "COST_OF_SALES_SERVICE",
    category: "サービス原価",
    amount: new Decimal(180000),
    description: "4月サービス原価",
  },
  {
    id: "cost10",
    year: 2024,
    month: 5,
    type: "COST_OF_SALES_SERVICE",
    category: "サービス原価",
    amount: new Decimal(190000),
    description: "5月サービス原価",
  },

  // 販管費
  {
    id: "cost11",
    year: 2024,
    month: 1,
    type: "SG_AND_A",
    category: "人件費",
    amount: new Decimal(500000),
    description: "1月人件費",
  },
  {
    id: "cost12",
    year: 2024,
    month: 2,
    type: "SG_AND_A",
    category: "人件費",
    amount: new Decimal(500000),
    description: "2月人件費",
  },
  {
    id: "cost13",
    year: 2024,
    month: 3,
    type: "SG_AND_A",
    category: "人件費",
    amount: new Decimal(500000),
    description: "3月人件費",
  },
  {
    id: "cost14",
    year: 2024,
    month: 4,
    type: "SG_AND_A",
    category: "人件費",
    amount: new Decimal(500000),
    description: "4月人件費",
  },
  {
    id: "cost15",
    year: 2024,
    month: 5,
    type: "SG_AND_A",
    category: "人件費",
    amount: new Decimal(500000),
    description: "5月人件費",
  },

  {
    id: "cost16",
    year: 2024,
    month: 1,
    type: "SG_AND_A",
    category: "オフィス費",
    amount: new Decimal(100000),
    description: "1月オフィス費",
  },
  {
    id: "cost17",
    year: 2024,
    month: 2,
    type: "SG_AND_A",
    category: "オフィス費",
    amount: new Decimal(100000),
    description: "2月オフィス費",
  },
  {
    id: "cost18",
    year: 2024,
    month: 3,
    type: "SG_AND_A",
    category: "オフィス費",
    amount: new Decimal(100000),
    description: "3月オフィス費",
  },
  {
    id: "cost19",
    year: 2024,
    month: 4,
    type: "SG_AND_A",
    category: "オフィス費",
    amount: new Decimal(100000),
    description: "4月オフィス費",
  },
  {
    id: "cost20",
    year: 2024,
    month: 5,
    type: "SG_AND_A",
    category: "オフィス費",
    amount: new Decimal(100000),
    description: "5月オフィス費",
  },

  {
    id: "cost21",
    year: 2024,
    month: 1,
    type: "SG_AND_A",
    category: "広告宣伝費",
    amount: new Decimal(80000),
    description: "1月広告宣伝費",
  },
  {
    id: "cost22",
    year: 2024,
    month: 2,
    type: "SG_AND_A",
    category: "広告宣伝費",
    amount: new Decimal(90000),
    description: "2月広告宣伝費",
  },
  {
    id: "cost23",
    year: 2024,
    month: 3,
    type: "SG_AND_A",
    category: "広告宣伝費",
    amount: new Decimal(100000),
    description: "3月広告宣伝費",
  },
  {
    id: "cost24",
    year: 2024,
    month: 4,
    type: "SG_AND_A",
    category: "広告宣伝費",
    amount: new Decimal(110000),
    description: "4月広告宣伝費",
  },
  {
    id: "cost25",
    year: 2024,
    month: 5,
    type: "SG_AND_A",
    category: "広告宣伝費",
    amount: new Decimal(120000),
    description: "5月広告宣伝費",
  },
]

// 予算モックデータ
export const budgets = [
  // 売上予算（月次）
  {
    id: "budget1",
    year: 2024,
    month: 1,
    quarter: null,
    type: "SALES",
    category: null,
    salesType: "LICENSE",
    amount: new Decimal(800000),
  },
  {
    id: "budget2",
    year: 2024,
    month: 2,
    quarter: null,
    type: "SALES",
    category: null,
    salesType: "LICENSE",
    amount: new Decimal(850000),
  },
  {
    id: "budget3",
    year: 2024,
    month: 3,
    quarter: null,
    type: "SALES",
    category: null,
    salesType: "LICENSE",
    amount: new Decimal(900000),
  },
  {
    id: "budget4",
    year: 2024,
    month: 4,
    quarter: null,
    type: "SALES",
    category: null,
    salesType: "LICENSE",
    amount: new Decimal(950000),
  },
  {
    id: "budget5",
    year: 2024,
    month: 5,
    quarter: null,
    type: "SALES",
    category: null,
    salesType: "LICENSE",
    amount: new Decimal(1000000),
  },

  {
    id: "budget6",
    year: 2024,
    month: 1,
    quarter: null,
    type: "SALES",
    category: null,
    salesType: "SERVICE",
    amount: new Decimal(400000),
  },
  {
    id: "budget7",
    year: 2024,
    month: 2,
    quarter: null,
    type: "SALES",
    category: null,
    salesType: "SERVICE",
    amount: new Decimal(450000),
  },
  {
    id: "budget8",
    year: 2024,
    month: 3,
    quarter: null,
    type: "SALES",
    category: null,
    salesType: "SERVICE",
    amount: new Decimal(500000),
  },
  {
    id: "budget9",
    year: 2024,
    month: 4,
    quarter: null,
    type: "SALES",
    category: null,
    salesType: "SERVICE",
    amount: new Decimal(550000),
  },
  {
    id: "budget10",
    year: 2024,
    month: 5,
    quarter: null,
    type: "SALES",
    category: null,
    salesType: "SERVICE",
    amount: new Decimal(600000),
  },

  // 費用予算（月次）
  {
    id: "budget11",
    year: 2024,
    month: 1,
    quarter: null,
    type: "COST_OF_SALES",
    category: "ライセンス原価",
    salesType: null,
    amount: new Decimal(240000),
  },
  {
    id: "budget12",
    year: 2024,
    month: 2,
    quarter: null,
    type: "COST_OF_SALES",
    category: "ライセンス原価",
    salesType: null,
    amount: new Decimal(255000),
  },
  {
    id: "budget13",
    year: 2024,
    month: 3,
    quarter: null,
    type: "COST_OF_SALES",
    category: "ライセンス原価",
    salesType: null,
    amount: new Decimal(270000),
  },
  {
    id: "budget14",
    year: 2024,
    month: 4,
    quarter: null,
    type: "COST_OF_SALES",
    category: "ライセンス原価",
    salesType: null,
    amount: new Decimal(285000),
  },
  {
    id: "budget15",
    year: 2024,
    month: 5,
    quarter: null,
    type: "COST_OF_SALES",
    category: "ライセンス原価",
    salesType: null,
    amount: new Decimal(300000),
  },

  {
    id: "budget16",
    year: 2024,
    month: 1,
    quarter: null,
    type: "COST_OF_SALES",
    category: "サービス原価",
    salesType: null,
    amount: new Decimal(160000),
  },
  {
    id: "budget17",
    year: 2024,
    month: 2,
    quarter: null,
    type: "COST_OF_SALES",
    category: "サービス原価",
    salesType: null,
    amount: new Decimal(180000),
  },
  {
    id: "budget18",
    year: 2024,
    month: 3,
    quarter: null,
    type: "COST_OF_SALES",
    category: "サービス原価",
    salesType: null,
    amount: new Decimal(200000),
  },
  {
    id: "budget19",
    year: 2024,
    month: 4,
    quarter: null,
    type: "COST_OF_SALES",
    category: "サービス原価",
    salesType: null,
    amount: new Decimal(220000),
  },
  {
    id: "budget20",
    year: 2024,
    month: 5,
    quarter: null,
    type: "COST_OF_SALES",
    category: "サービス原価",
    salesType: null,
    amount: new Decimal(240000),
  },

  {
    id: "budget21",
    year: 2024,
    month: 1,
    quarter: null,
    type: "SG_AND_A",
    category: "人件費",
    salesType: null,
    amount: new Decimal(480000),
  },
  {
    id: "budget22",
    year: 2024,
    month: 2,
    quarter: null,
    type: "SG_AND_A",
    category: "人件費",
    salesType: null,
    amount: new Decimal(480000),
  },
  {
    id: "budget23",
    year: 2024,
    month: 3,
    quarter: null,
    type: "SG_AND_A",
    category: "人件費",
    salesType: null,
    amount: new Decimal(480000),
  },
  {
    id: "budget24",
    year: 2024,
    month: 4,
    quarter: null,
    type: "SG_AND_A",
    category: "人件費",
    salesType: null,
    amount: new Decimal(480000),
  },
  {
    id: "budget25",
    year: 2024,
    month: 5,
    quarter: null,
    type: "SG_AND_A",
    category: "人件費",
    salesType: null,
    amount: new Decimal(480000),
  },

  {
    id: "budget26",
    year: 2024,
    month: 1,
    quarter: null,
    type: "SG_AND_A",
    category: "オフィス費",
    salesType: null,
    amount: new Decimal(120000),
  },
  {
    id: "budget27",
    year: 2024,
    month: 2,
    quarter: null,
    type: "SG_AND_A",
    category: "オフィス費",
    salesType: null,
    amount: new Decimal(120000),
  },
  {
    id: "budget28",
    year: 2024,
    month: 3,
    quarter: null,
    type: "SG_AND_A",
    category: "オフィス費",
    salesType: null,
    amount: new Decimal(120000),
  },
  {
    id: "budget29",
    year: 2024,
    month: 4,
    quarter: null,
    type: "SG_AND_A",
    category: "オフィス費",
    salesType: null,
    amount: new Decimal(120000),
  },
  {
    id: "budget30",
    year: 2024,
    month: 5,
    quarter: null,
    type: "SG_AND_A",
    category: "オフィス費",
    salesType: null,
    amount: new Decimal(120000),
  },

  {
    id: "budget31",
    year: 2024,
    month: 1,
    quarter: null,
    type: "SG_AND_A",
    category: "広告宣伝費",
    salesType: null,
    amount: new Decimal(100000),
  },
  {
    id: "budget32",
    year: 2024,
    month: 2,
    quarter: null,
    type: "SG_AND_A",
    category: "広告宣伝費",
    salesType: null,
    amount: new Decimal(100000),
  },
  {
    id: "budget33",
    year: 2024,
    month: 3,
    quarter: null,
    type: "SG_AND_A",
    category: "広告宣伝費",
    salesType: null,
    amount: new Decimal(100000),
  },
  {
    id: "budget34",
    year: 2024,
    month: 4,
    quarter: null,
    type: "SG_AND_A",
    category: "広告宣伝費",
    salesType: null,
    amount: new Decimal(100000),
  },
  {
    id: "budget35",
    year: 2024,
    month: 5,
    quarter: null,
    type: "SG_AND_A",
    category: "広告宣伝費",
    salesType: null,
    amount: new Decimal(100000),
  },

  // 四半期予算
  {
    id: "budget36",
    year: 2024,
    month: null,
    quarter: 1,
    type: "SALES",
    category: null,
    salesType: "LICENSE",
    amount: new Decimal(2550000),
  },
  {
    id: "budget37",
    year: 2024,
    month: null,
    quarter: 2,
    type: "SALES",
    category: null,
    salesType: "LICENSE",
    amount: new Decimal(2850000),
  },

  {
    id: "budget38",
    year: 2024,
    month: null,
    quarter: 1,
    type: "SALES",
    category: null,
    salesType: "SERVICE",
    amount: new Decimal(1350000),
  },
  {
    id: "budget39",
    year: 2024,
    month: null,
    quarter: 2,
    type: "SALES",
    category: null,
    salesType: "SERVICE",
    amount: new Decimal(1650000),
  },

  // 年間予算
  {
    id: "budget40",
    year: 2024,
    month: null,
    quarter: null,
    type: "SALES",
    category: null,
    salesType: "LICENSE",
    amount: new Decimal(12000000),
  },
  {
    id: "budget41",
    year: 2024,
    month: null,
    quarter: null,
    type: "SALES",
    category: null,
    salesType: "SERVICE",
    amount: new Decimal(6000000),
  },
  {
    id: "budget42",
    year: 2024,
    month: null,
    quarter: null,
    type: "COST_OF_SALES",
    category: "ライセンス原価",
    salesType: null,
    amount: new Decimal(3600000),
  },
  {
    id: "budget43",
    year: 2024,
    month: null,
    quarter: null,
    type: "COST_OF_SALES",
    category: "サービス原価",
    salesType: null,
    amount: new Decimal(2400000),
  },
  {
    id: "budget44",
    year: 2024,
    month: null,
    quarter: null,
    type: "SG_AND_A",
    category: "人件費",
    salesType: null,
    amount: new Decimal(5760000),
  },
  {
    id: "budget45",
    year: 2024,
    month: null,
    quarter: null,
    type: "SG_AND_A",
    category: "オフィス費",
    salesType: null,
    amount: new Decimal(1440000),
  },
  {
    id: "budget46",
    year: 2024,
    month: null,
    quarter: null,
    type: "SG_AND_A",
    category: "広告宣伝費",
    salesType: null,
    amount: new Decimal(1200000),
  },
  {
    id: "budget47",
    year: 2024,
    month: null,
    quarter: null,
    type: "OPERATING_PROFIT",
    category: null,
    salesType: null,
    amount: new Decimal(3600000),
  },
]
